### ISSUE TITLE
Need index on mdl_tool_crawler_url 'url' field

### ISSUE THREAD

**Issue by kristian-94** [catalyst/moodle-tool_crawler#113]
We have seen now that we are hammering the database with a query that causes a sequential table scan over many rows, every time it's run.

SELECT * FROM mdl_tool_crawler_url WHERE url = $1

 We’ll add an index to this ‘url’ field via the upgrade script which should help us a lot here and give much better performance.

**Comment by brendanheywood** [comment]
Bigger spec as this is a bit of a can of worms:

* [ ] First consider refactor all db read writes into the persistence api so there is less touch points:

https://docs.moodle.org/dev/Persistent

* [ ] the url fields is too long to index directly, so create a new field which store the hash of a url (use sha256)
* [ ] create index for that hash field
* [ ] all reads and writes need to keep that hash correct, but once a record is made it should never change anyway
* [ ] create migration upgrade script to populate the hash field

**Comment by kristian-94** [comment]
Trying to implement an index directly on the url field gives us:
> Default exception handler: Coding error detected, it must be fixed by a programmer: Invalid index definition in table {tool_crawler_url}: XMLDB_TYPE_CHAR field "url" can not be indexed because it is too long. Limit is 255 chars. 
Our url field is set to 1333 and needs to be that long, so we have to work around it.

**Comment by kristian-94** [comment]
This is now done and merged
