### ISSUE TITLE
Exclude url checking wrong filed

### ISSUE THREAD

**Issue by hdagheda** [catalyst/moodle-tool_crawler#120]
exclude url comparison against wrong filed value in classes/robot/crawler.php Line: 338
      `if (!self::is_external($url)) {
            $excludes = str_replace(PHP_EOL, ',', self::get_config()->excludemdlurl);
        } else {
            $excludes = str_replace(PHP_EOL, ',', self::get_config()->excludemdlurl);
        }`
should be
`if (!self::is_external($url)) {
            $excludes = str_replace(PHP_EOL, ',', self::get_config()->excludemdlurl);
        } else {
            $excludes = str_replace(PHP_EOL, ',', self::get_config()->excludeexturl);
        }`

**Comment by kristian-94** [comment]
@hdagheda  should this issue be closed?

**Comment by hdagheda** [comment]
Hi @kristian-94 yes.
