### ISSUE TITLE
unit test/travis error: only in moodle master branch

### ISSUE THREAD

**Issue by kristian-94** [catalyst/moodle-tool_crawler#122]
We get the following travis error in moodle master. Something has changed in core moodle that changes these tests. 

> 
> There were 2 failures:
> 
> 1) tool_crawler_robot_crawler_test::test_should_be_crawled with data set #4 ('/moodle/admin/settings.php?se...rawler', false)
> 
> Failed asserting that false is identical to true.
> 
> /home/travis/build/moodle/admin/tool/crawler/tests/phpunit/robot_crawler_test.php:448
> 
> /home/travis/build/moodle/lib/phpunit/classes/advanced_testcase.php:80
> 
> To re-run:
> 
>  vendor/bin/phpunit --configuration "tool_crawler_robot_crawler_test" admin/tool/crawler/tests/phpunit/robot_crawler_test.php
> 
> 2) tool_crawler_robot_crawler_test::test_should_be_crawled with data set #5 ('/moodle/admin', false)
> 
> Failed asserting that false is identical to true.
> 
> /home/travis/build/moodle/admin/tool/crawler/tests/phpunit/robot_crawler_test.php:448
> 
> /home/travis/build/moodle/lib/phpunit/classes/advanced_testcase.php:80
> 
> To re-run:
> 
>  vendor/bin/phpunit --configuration "tool_crawler_robot_crawler_test" admin/tool/crawler/tests/phpunit/robot_crawler_test.php

**Comment by kristian-94** [comment]
This is because of this line: https://github.com/catalyst/moodle-tool_crawler/blob/master/classes/robot/crawler.php#L287

In moodle master, $isexcluded = false here. But in other moodles, $isexcluded = true
The input params are the same, ie with dataset 4 
$excludes = ‘/admin’
$url = 'https://www.example.com/moodle/admin/settings.php?section=tool_crawler'

Something in core moodle has changed in the profiling_string_matches() function.

**Comment by kristian-94** [comment]
It will be because of this tracker: https://tracker.moodle.org/browse/MDL-65349

@brendanheywood , do we need to be including wildcards somewhere now?

**Comment by kristian-94** [comment]
Solution: instead of calling profiling_string_matches, we should just copy the entire old function from before this tracker into the crawler 
bump the version
copy the unit tests from this tracker into crawler

**Comment by brendanheywood** [comment]
cools
