### ISSUE TITLE
Poor UX for non-site admin users viewing course level reports

### ISSUE THREAD

**Issue by jonlucholmes** [catalyst/moodle-tool_crawler#152]
The UX for non-site admin users that are viewing the link crawler reports is poor and results in users being sent back to the Moodle dashboard.

Steps to recreate:
1. Access Moodle as a non site-admin user
2. Access a course that the account is enrolled onto
3. In the administration block, navigate to: Course Administration > Reports > Link crawler robot
4. Open any one of the four reports
5. Click any of the tabs at the top of the page
6. Error message appears directing users with continue button that takes users back to dashboard

![image](https://user-images.githubusercontent.com/9091061/100628643-569c8380-3320-11eb-8645-50a0726c7411.png)

This error is caused by the user account not being a site admin and being unable to view the overall reports for the entire site. However, the report they'd see at course level contains tab at the top which all link to configuration pages and reports intended for site administrators.

![link-crawler-ux-issue](https://user-images.githubusercontent.com/9091061/100629028-c27eec00-3320-11eb-8200-3d28f86414f6.png)

This is a poor user experience as naturally end users viewing their course level link crawler report will use the tabs at the top to navigate between reports rather than the report links within the administration block. Likewise the tabs at the top also include 'Settings' and 'Summary' which shouldn't be an option for those who aren't site administrators.

The administration block correctly contains links to the course specific report, for example: /admin/tool/crawler/report.php?report=recent&course=1234 whereas clicking the 'Recently crawled' tab only links to /admin/tool/crawler/report.php?report=recent

**Comment by brendanheywood** [comment]
+1

**Comment by cameron1729** [comment]
Closing this one since https://github.com/catalyst/moodle-tool_crawler/pull/159 has been merged
