### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by behoof** [catalyst/moodle-tool_crawler#21]
L.s.

Clicking on the robot status button gives a database error. So I could not create the moodlebot user.

Debugging info:

SELECT COUNT(*)
FROM mdl_tool_crawler_url b
JOIN mdl_tool_crawler_edge l ON l.b = b.id
WHERE b.httpcode != '200'
[array (
)]
Error code: dmlreadexception
Stack trace:
line 474 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 1088 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
line 1527 of /lib/dml/moodle_database.php: call to mysqli_native_moodle_database->get_records_sql()
line 1600 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
line 398 of /admin/tool/crawler/classes/robot/crawler.php: call to moodle_database->get_field_sql()
line 53 of /admin/tool/crawler/index.php: call to tool_crawler\robot\crawler->get_pages_withbroken_links()

**Comment by brendanheywood** [comment]
Can you provide a bit info about what you've done leading up to this? Is the tool correctly installed, ie the upgrade complete ok?

**Comment by behoof** [comment]
Hi Brendan,

I installed the tool as usual: no errors and warnings. I ended after the upgrade of the database in the setting screen and saved it. In the setting screen I changed the password and saved the settings.

I see crawled url's sections, but I cannot open the status window without having the error as mentioned.

**Comment by brendanheywood** [comment]
Thisis weird, I can't reproduce this locally at all. Can you confirm the version of the plugin you are on, and the version of moodle you are on, and try grabbing the latest code from this repo instead of the moodle plugins directory (if that is the way you installed it)

**Comment by JensReineking** [comment]
Hi Brendan, Hi Behoof,
As far as I can see, the error messages above are the same I got last fall (https://github.com/central-queensland-uni/moodle-tool_crawler/issues/6).

I was finally able to come back to it and check the database - and all tool_crawler_* tables seem to be missing from our database.

**Comment by brendanheywood** [comment]
Again this is all very weird, there is something fundamentally busted with how it is being installed. The continuous integration travis scripts install this and run the unit tests on every change so this isn't a code issue. All I can suggest is going to the admin tools page and uninstalling it and then go back to the admin notifications page to reinstall it and see if it installs properly.

/admin/tools.php

If that fails then also try uninstalling it, then installing via the command line instead, and if it fails then dump it's output into this issue. Instructions here:

https://docs.moodle.org/32/en/Administration_via_command_line#Upgrading

Please make sure the moodle debugging level is on full in config.php : 

```
@error_reporting(E_ALL | E_STRICT); // NOT FOR PRODUCTION SERVERS!
@ini_set('display_errors', '1');    // NOT FOR PRODUCTION SERVERS!
$CFG->debug = (E_ALL | E_STRICT);   // === DEBUG_DEVELOPER - NOT FOR PRODUCTION SERVERS!
$CFG->debugdisplay = 1;             // NOT FOR PRODUCTION SERVERS!
```

**Comment by JensReineking** [comment]
I unistalled and re-installed (directly from repository and via upload of zip-file) and still have the same problem.

I haven't done the installation via command line because I have no clue how the command line works. So the documentation you referenced does not help me.
Same goes for GIT.
Sorry.

**Comment by brendanheywood** [comment]
Try using this instead:

https://github.com/central-queensland-uni/moodle-tool_crawler/archive/master.zip

**Comment by JensReineking** [comment]
Herzlichen Dank!
Thank you very much, now it works!

**Comment by brendanheywood** [comment]
Note this was due to the plugins directory zip being out of date with this git repo
