### ISSUE TITLE
How to reset/debug Link Crawler?

### ISSUE THREAD

**Issue by certifycrm** [catalyst/moodle-tool_crawler#29]
My link crawler stopped working on Nov 26th. It had been running for 740:08:32 and not processed any links so I reset it.  On Dec 26th I checked it again and it had been running for 201:29:33 and not processed any links so I reset again. Where does it report any errors so I can investigate further and what should I be looking for?   

Current Moodle version: Moodle 3.2.6+ (Build: 20171208)
Link crawler robot version: 2017042700

Robot status (after Reset Progress today):
--
Bot user | moodlebot \| Good \| User account \| Roles
Progress | 100.00% ETA in Tuesday, 26 December 2017, 8:08 PM \| Reset Progress
Current crawl started at | Never run
Last crawl ended at | Never finished
Last crawl process | -
Last queue size | 0
Total links | 0
Queued URL's | 0
Recently crawled URL's | 0
Broken links / URLs | 0 / 0
Big / slow links | 0

Progress logs:

Crawl start	Crawl end	Duration	Cron ticks	Total urls	Total links	Broken links / URLs	Big / slow links
Dec 18, 10:39:02	-	201:29:33	0	0	0	0	0
Nov 26, 00:00:03	-	740:08:32	0	0	0	0	0
Nov 21, 18:00:02	Nov 25, 18:00:09	96:00:07	17	1,694	11,591	4	2
Nov 18, 00:00:06	Nov 21, 12:00:42	84:00:36	15	1,689	11,558	7	2
Nov 14, 00:00:07	Nov 17, 18:00:35	90:00:28	16	1,687	11,538	7	2

**Comment by brendanheywood** [comment]
Turn off the task in the admin gui, then run the crawler from the cli which turns on verbose mode and should spit out something hopefully more useful:

```
php admin/tool/crawler/cli/crawler.php
```

It is likely some weird edge case where the crawler is dying on parsing some particular page. In the short term you can probably just exclude that url, and then log full details here once you know more

**Comment by certifycrm** [comment]
Thanks Brendan, it was stopping on my Twitter link as I had put a special character to display an icon after my Twitter name. Once I removed that it was ok. thanks for the prompt reply!

**Comment by brendanheywood** [comment]
Ok that sounds like some sort of unicode parsing edge case issue, can you please post the twitter url and the raw unicode chars here and we'll try and reproduce it and fix it some time in the new year

**Comment by certifycrm** [comment]
I've removed it now but any character from here: http://getemoji.com/ - use any char from the very last group, just copy and paste one to a twitter profile - edit the profile and add it to the end of the name.

**Comment by brendanheywood** [comment]
This should now be fixed, closing this
