### ISSUE TITLE
Crawler activity distorts course activity report (report_outline)

### ISSUE THREAD

**Issue by nicoroeser** [catalyst/moodle-tool_crawler#78]
While the crawler is working, Moodle obviously creates log entries for the accesses made by the bot user. This results in wrong statistics in reports: the course activity report at `/report/outline/index.php?id=COURSEID` shows higher access counts because the bot accesses are counted in.

Strictly speaking, the statistics are not _wrong_ as the bot _does_ access the pages, but they are rather not what administrators and teachers in courses expect and would like to see.

At the moment, I do not have a good idea what could be done about this. I’m raising it here so that the topic can be discussed. Useful insights should be documented in `README.md`.

**Comment by brendanheywood** [comment]
My general thoughts on this is that we can't and shouldn't do anything in the crawler tool. This same concept could apply to a bunch of other types of reports.

The best way to handle this is that the report's can break down traffic in some way, probably by role, eg show student traffic, show marker traffic, course manager traffic etc. If it leverages the roles then that would be the best.

Another approach to investigate is looking at the useragent->is_web_crawler() method. In theory you could have a course which is publicly visible and google would hit it, and you would want to filter out these hits too. As long as the bot UA string for the crawler is matching then we have clean common way to exclude all sorts of stuff where moodle hits itself. ie the other obvious place this would apply is the simplepie rss library. I'll open a tracker:

https://tracker.moodle.org/browse/MDL-66166

We should also refactor the way curl is called to use the moodle curl proxy:

https://github.com/catalyst/moodle-tool_crawler/blob/master/classes/robot/crawler.php#L892

**Comment by abias** [comment]
Hi Brendan,

thank you for your reply.

I have checked https://tracker.moodle.org/browse/MDL-66166 which you have raised and linked and have also checked https://tracker.moodle.org/browse/MDL-66167 which you have raised bot not linked here.

From my point of view, the discussion should move to there as I agree now that you can't do anything in the crawler tool about this issue. 

So, this issue could basically be closed - but there was this comment from you:

> We should also refactor the way curl is called to use the moodle curl proxy:
> 
> https://github.com/catalyst/moodle-tool_crawler/blob/master/classes/robot/crawler.php#L892

Is this something which you want to handle within this issue or within a separate issue?

Thanks,
Alex

**Comment by brendanheywood** [comment]
No I suspect that comment is out of date. Some of the advanced curl stuff that you guys contributed I don't think is possible using the simplified moodle curl api. It might work but it's busy work. The main feature that would drive that would be honoring the outgoing proxy moodle setting. No one has asked for it yet so I'll cross that bridge when we need to.
