### ISSUE TITLE
Slowdown in administration part

### ISSUE THREAD

**Issue by t-dupuy** [catalyst/moodle-tool_crawler#96]
Hello and thank you for making your plugin available.

However, we noticed that this plugin caused a significant slowdown in the administration part (only).

For example, the moodle/admin/search.php page now takes 25s to display compared to 4s without the plugin.

Are there any settings to be made to avoid this problem?

We want the plugin to run only the weekend on all active courses in a year, so we have set up the cron tasks like this: 

![image](https://user-images.githubusercontent.com/52969834/67488025-4e7b0a80-f66f-11e9-90cf-cbd495ef386e.png)

The plugin version is : 2018070200

Thank you for your feedback.

**Comment by brendanheywood** [comment]
I'm pretty sure it was this:

https://github.com/catalyst/moodle-tool_crawler/blob/master/settings.php#L146

https://github.com/catalyst/moodle-tool_crawler/commit/c10c5e04488b49593f95eb4c7ad7c186a8a7410e

@kristian-94 do you also see this perf impact?

**Comment by kristian-94** [comment]
Hi @brendanheywood  and @t-dupuy  ,
Yes you will get a slow page if you have a high value for the setting: "Days of recent activity" recentactivity
If you set this to a small number (eg. 1), then your pages will be fast again. 
I will make a fix so that this doesn't happen in settings pages though.

**Comment by brendanheywood** [comment]
Yes this should not be done in the settings

**Comment by t-dupuy** [comment]
Thank you !

**Comment by abias** [comment]
I would like to report that we ran into the same problem.
The idea behind showing the number within the settings description is appreciated - with the number shown there, you can directly see the impact of the configured value for recentactivity.

However, there is a huge downside as this number is collected everytime the plugin's settings.php is processed - which happens on all site administration pages as well as on the site notification page /admin/index.php.

Thus, I would like to recommend to remove this number collecting as already commited to the bugfix branch or at least restrict the number collecting to the case when the tool_crawler settings page is shown.

Thanks,
Alex

**Comment by abias** [comment]
I have seen that the patch by @kristian-94 has been merged into master in the meantime.

Then the branch https://github.com/catalyst/moodle-tool_crawler/tree/issue96 could be deleted and this issue could be closed or am I wrong?

**Comment by kristian-94** [comment]
You're right, this issue has been fixed now and merged to master. Closing this issue, thanks for reporting it @t-dupuy  :+1:
